<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
	<title>MySQL++ Reference Manual</title>
	<meta http-equiv="Content-type" content="text/html;charset=iso-8859-1">
	<link href="doxygen.css" rel="stylesheet" type="text/css">
	<link href="refman.css" rel="stylesheet" type="text/css">
</head>
<body>
<!-- Generated by Doxygen 1.4.7 -->
<div class="tabs">
  <ul>
    <li><a href="index.html"><span>Main&nbsp;Page</span></a></li>
    <li><a href="namespaces.html"><span>Namespaces</span></a></li>
    <li id="current"><a href="annotated.html"><span>Classes</span></a></li>
    <li><a href="files.html"><span>Files</span></a></li>
  </ul></div>
<div class="tabs">
  <ul>
    <li><a href="annotated.html"><span>Class&nbsp;List</span></a></li>
    <li><a href="hierarchy.html"><span>Class&nbsp;Hierarchy</span></a></li>
    <li><a href="functions.html"><span>Class&nbsp;Members</span></a></li>
  </ul></div>
<div class="nav">
<b>mysqlpp</b>::<a class="el" href="classmysqlpp_1_1UseQueryError.html">UseQueryError</a></div>
<h1>mysqlpp::UseQueryError Class Reference</h1><!-- doxytag: class="mysqlpp::UseQueryError" --><!-- doxytag: inherits="mysqlpp::Exception" --><a class="el" href="classmysqlpp_1_1Exception.html">Exception</a> thrown when something goes wrong in processing a "use" query.  
<a href="#_details">More...</a>
<p>
<code>#include &lt;<a class="el" href="exceptions_8h-source.html">exceptions.h</a>&gt;</code>
<p>
Inheritance diagram for mysqlpp::UseQueryError:<p><center><img src="classmysqlpp_1_1UseQueryError__inherit__graph.png" border="0" usemap="#mysqlpp_1_1UseQueryError__inherit__map" alt="Inheritance graph"></center>
<map name="mysqlpp_1_1UseQueryError__inherit__map">
<area href="classmysqlpp_1_1Exception.html" shape="rect" coords="20,5,172,32" alt="">
</map>
<center><font size="2">[<a href="graph_legend.html">legend</a>]</font></center>Collaboration diagram for mysqlpp::UseQueryError:<p><center><img src="classmysqlpp_1_1UseQueryError__coll__graph.png" border="0" usemap="#mysqlpp_1_1UseQueryError__coll__map" alt="Collaboration graph"></center>
<map name="mysqlpp_1_1UseQueryError__coll__map">
<area href="classmysqlpp_1_1Exception.html" shape="rect" coords="20,96,172,123" alt="">
</map>
<center><font size="2">[<a href="graph_legend.html">legend</a>]</font></center><a href="classmysqlpp_1_1UseQueryError-members.html">List of all members.</a><table border="0" cellpadding="0" cellspacing="0">
<tr><td></td></tr>
<tr><td colspan="2"><br><h2>Public Member Functions</h2></td></tr>
<tr><td class="memItemLeft" nowrap align="right" valign="top"><a class="anchor" name="8a6b5031294cce3b297edab7a7c9ab03"></a><!-- doxytag: member="mysqlpp::UseQueryError::UseQueryError" ref="8a6b5031294cce3b297edab7a7c9ab03" args="(const char *w=&quot;&quot;)" -->
&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classmysqlpp_1_1UseQueryError.html#8a6b5031294cce3b297edab7a7c9ab03">UseQueryError</a> (const char *w=&quot;&quot;)</td></tr>

<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Create exception object. <br></td></tr>
</table>
<hr><a name="_details"></a><h2>Detailed Description</h2>
<a class="el" href="classmysqlpp_1_1Exception.html">Exception</a> thrown when something goes wrong in processing a "use" query. 
<p>
<hr>The documentation for this class was generated from the following file:<ul>
<li><a class="el" href="exceptions_8h-source.html">exceptions.h</a></ul>
<hr size="1"><address style="align: right;"><small>Generated on 10 Dec 2013 for MySQL++ by&nbsp;
<a href="http://www.doxygen.org/index.html">
<img src="doxygen.png" alt="doxygen" align="middle" border="0"></a> 1.4.7 </small></address>
</body>
</html>
